
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# Driver
db.driver = 

# --- Database students ---
student.db.url=
student.db.username=
student.db.password=

# --- Database users ---
user.db.url=
user.db.username=
user.db.password=

#Secret password for the server
jwt.secret=