/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/UnitTests/JUnit5TestClass.java to edit this template
 */
package org.centrale.pappl.projetpapplstingtf.config;

import org.centrale.pappl.projetpapplstingtf.ProjetPapplStingTfeApplication;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.test.web.servlet.MockMvc;

import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Integration Test for SecurityConfig.
 * <p>
 * Instead of manually calling methods (which requires complex mocking),
 * we verify that Spring successfully loads the security context and that
 * the beans are correctly configured.
 * </p>
 * @author srodr
 */
@SpringBootTest(classes = ProjetPapplStingTfeApplication.class)
@AutoConfigureMockMvc
public class SecurityConfigTest {

    @Autowired
    private ApplicationContext context;

    @Autowired
    private MockMvc mockMvc;

    // We inject the beans to verify they were created successfully by SecurityConfig
    @Autowired(required = false) // Optional, so the test fails with assertion, not dependency error
    private PasswordEncoder passwordEncoder;

    @Autowired(required = false)
    private AuthenticationManager authManager;

    @Autowired(required = false)
    private UserDetailsService userDetailsService;

    @Autowired(required = false)
    private SecurityFilterChain securityFilterChain;

    public SecurityConfigTest() {
    }

    /**
     * Test that all critical Security Beans are loaded into the Context.
     * This replaces the individual unit tests generated by NetBeans.
     */
    @Test
    public void testSecurityBeansAreLoaded() {
        System.out.println("Test: Security Beans Existence");

        assertNotNull(passwordEncoder, "PasswordEncoder bean should be loaded");
        assertNotNull(authManager, "AuthenticationManager bean should be loaded");
        assertNotNull(userDetailsService, "UserDetailsService bean should be loaded");
        assertNotNull(securityFilterChain, "SecurityFilterChain bean should be loaded");

        // Verify that BCrypt is actually being used
        assertTrue(passwordEncoder.encode("test").startsWith("$2a$"), 
                "PasswordEncoder should be BCrypt");
    }

    /**
     * Test that the Security Filter Chain is actually enforcing rules.
     * Replaces 'testSecurityFilterChain' with a behavioral test.
     */
    @Test
    public void testSecurityRules_PublicEndpoints() throws Exception {
        System.out.println("Test: Public Endpoints Access");

        // /login should be public (200 OK)
        mockMvc.perform(get("/login"))
                .andExpect(status().isOk());
    }

    /**
     * Test that private endpoints are protected.
     */
    @Test
    public void testSecurityRules_PrivateEndpoints() throws Exception {
        System.out.println("Test: Private Endpoints Protection");

        // Accessing a random API without token should be blocked (302 Redirect to login or 401)
        mockMvc.perform(get("/api/private/data"))
                .andExpect(status().is3xxRedirection()); 
    }
}