name: Java CI with Maven and SonarCloud

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "main", "develop"]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para que Sonar vea el historial de git

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven # Truco pro: esto activa el caché automáticamente sin escribir tanto código extra

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Pappl-Project_Projet-PAPPL-Soutenances-STING-et-TFEean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Pappl-Project_Projet-PAPPL-Soutenances-STING-et-TFE